# Generated by Django 4.2.6 on 2023-10-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(default='profile.jpg', upload_to='post/'),
            preserve_default=False,
        ),
    ]
